name: env-jupyterlite-xeus-demo
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - xeus-sqlite
  - ipywidgets
  - ipyevents
  - ipympl
  - matplotlib
  - plotly
  - sympy
  - pandas
  - numpy
  - statsmodels
  - scipy
  - scikit-learn
  - pillow
  - pip:
    # Installing a python package that ships a lab extension under share/
    - ipycanvas
    # Installing a pure python package
    - py2vega
